### ISSUE TITLE
Fails on AMIP output

### ISSUE THREAD

**Issue by lwhorowitz** [jkrasting/gfdlvitals#8]
I tried running the new gfdlvitals script on the latest AMIP simulation, but it failed without producing any *.db files. The stdout file is:

/home/Larry.Horowitz/ESM4/ESM4.2/ESM4_longamip_D1_am4p2_proto7b_whiteCapsAlbedo_salt_SIS2/gfdl.ncrc3-intel18-prod-openmp/stdout/postProcess/ESM4_longamip_D1_am4p2_proto7b_whiteCapsAlbedo_salt_SIS2_refineDiag_18700101.o16179390

The relevant bit is:
/home/mdteam/anaconda/envs/gfdlvitals_202103/bin/gfdlvitals -s 1870 -e 1870 -o /home/Larry.Horowitz/ESM4/ESM4.2/ESM4_longamip_D1_am4p2_proto7b_whiteCapsAlbedo_salt_SIS2/gfdl.ncrc3-intel18-prod-openmp/db -g /archive/gold/datasets/OM4_05/mosaic_c96.v20180227.tar /archive/Larry.Horowitz/ESM4/ESM4.2/ESM4_longamip_D1_am4p2_proto7b_whiteCapsAlbedo_salt_SIS2/gfdl.ncrc3-intel18-prod-openmp/history
Matplotlib is building the font cache; this may take a moment.
Dmgetting files ...
Complete!
Processing 18700101
18700101.atmos_month.nc
18700101.atmos_co2_month.nc
18700101.atmos_month_aer.nc
18700101.aerosol_month_cmip.nc
18700101.land_month.nc
18700101.ice_month.nc
Traceback (most recent call last):
  File "/home/mdteam/anaconda/envs/gfdlvitals_202103/lib/python3.8/site-packages/xarray/core/dataset.py", line 1305, in _construct_dataarray
    variable = self._variables[name]
KeyError: 'CELL_AREA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mdteam/anaconda/envs/gfdlvitals_202103/bin/gfdlvitals", line 186, in <module>
    process_year(cliargs, _infile)
  File "/home/mdteam/anaconda/envs/gfdlvitals_202103/bin/gfdlvitals", line 114, in process_year
    gfdlvitals.models.CM4.routines(args, infile)
  File "/home/mdteam/anaconda/envs/gfdlvitals_202103/lib/python3.8/site-packages/gfdlvitals/models/CM4.py", line 56, in routines
    averagers.ice.xr_average(fyear, tar, modules)
  File "/home/mdteam/anaconda/envs/gfdlvitals_202103/lib/python3.8/site-packages/gfdlvitals/averagers/ice.py", line 59, in xr_average
    _area = ds_grid["CELL_AREA"] * 4.0 * np.pi * (earth_radius ** 2)
  File "/home/mdteam/anaconda/envs/gfdlvitals_202103/lib/python3.8/site-packages/xarray/core/dataset.py", line 1409, in __getitem__
    return self._construct_dataarray(key)
  File "/home/mdteam/anaconda/envs/gfdlvitals_202103/lib/python3.8/site-packages/xarray/core/dataset.py", line 1307, in _construct_dataarray
    _, name, variable = _get_virtual_variable(
  File "/home/mdteam/anaconda/envs/gfdlvitals_202103/lib/python3.8/site-packages/xarray/core/dataset.py", line 171, in _get_virtual_variable
    ref_var = variables[ref_name]
KeyError: 'CELL_AREA'
set refineStatus = 1
if ( 1 < 0 ) then
if ( 1 ) then
echo ERROR: RefineDiag script got an error status 1
ERROR: RefineDiag script got an error status 1

The previous version of the data ingester script would just issue warning messages:
WARNING: Unable to open file 19990101.ice_static.nc
WARNING: Unable to open file 19990101.ocean_static.nc
WARNING: Unable to open file 19990101.ocean_scalar_annual.nc
WARNING: Unable to open file 19990101.ocean_annual_z.nc

but still complete cleanly and produce the *.db files and copy them to the output directory.

**Comment by lwhorowitz** [comment]
Note that the history tarballs for the above AMIP run do not contain ice_static files (only ice_month) or any ocean history files.

**Comment by jkrasting** [comment]
@lwhorowitz - thanks.  This is an interesting issue.  When running SIS in AMIP mode, the grid information is output in a file called `YYYYMMDD.sea_ice_geometry.nc` just after initialization.  This pull request now adds support for this file, but I have not yet verified the calculation.

This file is only written once at initialization, so it is only available for the first year of an AMIP simulation. Subsequent years are missing this information.  I've added a fix so that it fails more gracefully and skips the sea ice calculation if it the code cannot find a suitable cell area field.

I am not sure if `CELL_AREA` can be added to the diag_table in AMIP mode.  If it can be added to the `ice_month` output stream, that will solve the issue.  If not, we need to think about getting the sea ice area field from another place, but that breaks the paradigm that a history tarball is a self-contained unit that has all of the information needed to calculate a global mean.  I am not keen on adding external dependencies.

In AMIP mode, is the sea ice prescribed?  Are sea ice scalars a high priority for the configuration?

**Comment by lwhorowitz** [comment]
Thanks, @jkrasting! I can test whether I can output `CELL_AREA` in AMIP mode. If so, I will add it to `ice_month`.

But, since sea ice is prescribed in AMIP runs, ice diagnostics are NOT a high priority. So, skipping ice diagnostics entirely is certainly a fine option, if the required fields are not available. I agree with you that we don't want to break the clean paradigm of getting all of the required information from the history tarball. As far as I am concerned, my main priority is to make sure that a failure in the ice processing doesn't prevent other model components (e.g., land) from being processed successfully.

**Comment by jkrasting** [comment]
Fixed by #9.
